name = "BinaryTrees"
uuid = "289e92be-c05a-437b-9e67-5b0c799891f8"
authors = ["Elias Carvalho <eliascarvdev@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"

[compat]
AbstractTrees = "0.4"
julia = "1.10"
